version: '3.7'

services:
  webserver:
    build:
      context: .
    volumes:
      - static_data:/vol/web
    environment: 
      - SECRET_KEY=samplesecretkey123
      - ALLOWED_HOSTS=127.0.0.1,localhost 

  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
    ports:
      - "80:80"
    depends_on:
      - webserver

volumes:
  static_data: